services:
  - type: web
    name: emoc
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: TOKEN
        sync: false
      - key: PREFIX
        value: "!"
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: OWNER_ID
        sync: false
